name: .NET 9 Build and Download

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Clean
        run: dotnet clean

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Prepare files for download (Publish)
        run: dotnet publish --configuration Release --no-build -o ./app-build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-dotnet9-app-build
          path: ./app-build/
          retention-days: 7
